### ISSUE TITLE
Ensure that programs are the same on the website

### ISSUE THREAD

**Issue by VicaWorth** [VicaWorth/csci-36#10]

**Comment by khasek** [comment]
There were a number of discrepancies between the programs listed on butte.edu and the programs listed in our database. These have been detailed in the attached text file.

[program_discrepancies.txt](https://github.com/VicaWorth/csci-36/files/9701970/program_discrepancies.txt)

Additional Note: The data I was viewing listed the "createdAt" date for all programs as 2022-09-27.

**Comment by benlazzero** [comment]
Fetch programs is getting data from this page 'https://programs.butte.edu/ProgramList/All/10/false'. The discrepancies are apparent on this one. 

I think telling the scraper to fetch the newer data on 'https://programs.butte.edu/ProgramList/All/12/false' resolves the issue.

I have not replaced the url on scraper.js line 13 to check yet though.

**Comment by benlazzero** [comment]
Ran scraper with updated link and everything is there, I think we can close this issue
