### ISSUE TITLE
Clean up scraper

### ISSUE THREAD

**Issue by VicaWorth** [VicaWorth/csci-36#11]
The scraper right now runs very slowly. Is there someway we can speed this up? A way to enhance it?

This step doesn't necessarily have concrete results, but I think talking with one another is a good idea!

**Comment by benlazzero** [comment]
I'm going to be looking into the scraper this week to see what's going on. If I see a way to easily turn it into a class I will which may make it a little nicer to debug with the missed programs/departments it's delivering. I'm also thinking maybe that module doesn't handle the DB write and just returns a list to be written or something. I'm thinking separating these concerns will make life easier down the road as well.
