### ISSUE TITLE
Create Tests

### ISSUE THREAD

**Issue by VicaWorth** [VicaWorth/csci-36#20]
**For Testers + UX**
These do not have to be incredibly in depth at this point. For the most part we want to test if what we already have works correctly.

Frankly, not too much seems broken right now. So it might be a good idea to see things like:

1. How long does a scrape take?
2. Notice any slow downs?
3. Notice any usability issues? Like something that doesn't seem quite right?

**Comment by khasek** [comment]
Here is our current test plan: https://docs.google.com/document/d/1oGDTuu91bi567rkcPJvo7NkwAy7Iv6Anca1fKPkFxAc/edit#heading=h.cfsu8rw32hqg

If anyone would like to add, remove, or change a test, the document should be open to editing by anyone with the link. Alternatively, I'm happy to make changes myself. Discord PMs are the best way to get ahold of me.
