### ISSUE TITLE
Decide bug tracking method

### ISSUE THREAD

**Issue by VicaWorth** [VicaWorth/csci-36#21]
This is pretty simple, but we just need to know how we will track bugs. 

We can use Zenhub, Google Forms, Github, its up to you.

**Comment by khasek** [comment]
Here's a bug report I made on Google Forms:
https://docs.google.com/forms/d/1oieRaW7f-ovza0TzJV2uYU2mpN5K2-LgghmhnEmF0v8/edit

And here's the spreadsheet the report sends data to:
https://docs.google.com/spreadsheets/d/1bgnW1F7fxztyTgHTKJFAEqMXjWHt8w_NwMaPcE9aUZA/edit?resourcekey#gid=2000943100
