### ISSUE TITLE
Ensure that departments are the same as on the website

### ISSUE THREAD

**Issue by VicaWorth** [VicaWorth/csci-36#9]

**Comment by khasek** [comment]
I finished comparing departments. They're mostly the same on the database as they are on the website, with one difference, but the department chairs have a lot of discrepancies. I put my findings in this file:

[departments.txt](https://github.com/VicaWorth/csci-36/files/9702630/departments.txt)

**Comment by benlazzero** [comment]
Referring to issue #10, that solution resolved this issue as well
